### ISSUE TITLE
conda env create -f environment.yaml

### ISSUE THREAD

**Issue by 3414391918** [declare-lab/trust-align#1]
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement en-core-web-sm==3.7.1 (from versions: none)
ERROR: No matching distribution found for en-core-web-sm==3.7.1

**Comment by shanghongsim** [comment]
Thank you for trying our codebase! Sincere apologies for the issues faced during setup. The issue should be resolved with the latest commit: 8efd873fd90034d998f3b68493de40cfabe95b2d . 

Warm regards,
Shang Hong
